# Generated by Django 2.2.13 on 2021-03-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
