# Generated by Django 2.2.13 on 2021-04-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210331_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='bandera',
            field=models.BooleanField(default=False),
        ),
    ]
